#!/usr/bin/python3
# CMPD: Terminal Compound Parser

import re
import json
import os

import rich
from rich.prompt import Prompt
from rich.text import Text

CURRENT_DIR = '/home/ddmin/Code/Python/Chemistry'

def find_molar_mass(compound):
    p = re.compile(r'([A-Z][a-z]?)([0-9]*)')
    matches = re.findall(p, compound)

    d = {}
    for match in matches:
        d.setdefault(match[0], 0)

        if match[1] != '':
            d[match[0]] += int(match[1])
        else:
            d[match[0]] += 1

    molarmass = 0
    for x, y in d.items():
        molarmass += elements[x] * y

    return molarmass

def mm(compound):

    p = re.compile(r'\((\w+)\)([0-9])*')
    matches = re.findall(p, compound)

    compound = re.sub(p, '', compound)

    molarmass = find_molar_mass(compound)

    for match in matches:
        if match[1] == '':
            n = 1
        else:
            n = int(match[1])

        molarmass += find_molar_mass(match[0]) * n

    return molarmass

with open(os.path.join(CURRENT_DIR, "Element JSON/atomic_weights.json"), "r") as f:
        elements = json.load(f)

def main():

    title = Text(justify='center', style='#39FF14')

    title.append(r'                        __         ° ' + '\n')
    title.append(r'    _________ ___  ____  ____/ /      _     ° __' + '\n')
    title.append(r'   / ___/ __ `__ \/ __ \/ __  /       |  °    |/' + '\n')
    title.append(r' / /__/ / / / / / /_/ / /_/ /        |~*~~~~~|' + '\n')
    title.append(r' \___/_/ /_/ /_/ .___/\__,_/         | .   * |' + '\n')
    title.append(r'               /_/                   |*___.__|')
    rich.print(title)

    subtitle = Text(justify='center')
    subtitle.append('terminal compound parser', style='underline #add8e6')
    rich.print(subtitle)

    compound = 'compound'
    while compound:
        try:
            compound = input(">> ")
            if compound:
                print(f'Molar Mass: {mm(compound)}')
                print()
        except:
            pass

if __name__ == "__main__":
    main()
